### PR TITLE
Setup circleci

### PR DESCRIPTION
**Pull request by hanachin**
I use 1agileware-jp/redmine-plugin@0.0.101 to test the plugin.
https://circleci.com/orbs/registry/orb/agileware-jp/redmine-plugin

build example: https://circleci.com/workflow-run/2ed550de-1031-497e-a5d9-5b573ab068a6

- Add `rails_kwargs_testing` for Redmine 3.4/3.3/3.2 for test code compatibility
- Use `ActionController::TestCase` for Redmine 3.3/3.2
- Test against Redmine 4.0/3.4/3.3/3.2

### CODE REVIEW

**Comment by ishikawa999** [comment]
Thank you for making a pull request.
I merged this pull request.

Since I have never used CircleCI,
I may have to contact you again if I have any problems :persevere:

**Comment by hanachin** [comment]
If you have any problem, please feel free to ask me 😄👍

**Comment by ishikawa999** [comment]
note: CircleCI tests will probably not succeed until I merge the develop branch into the master branch.

**Comment by hanachin** [comment]
This CircleCI configuration uses reusable orb, maybe you need to enable pipelines in project settings to run the test (see Getting Started with Config Reuse step 1.)
https://circleci.com/docs/2.0/reusing-config/

**Comment by ishikawa999** [comment]
> This CircleCI configuration uses reusable orb, maybe you need to enable pipelines in project settings to run the test (see Getting Started with Config Reuse step 1.)
> https://circleci.com/docs/2.0/reusing-config/

@hanachin 
Thank you for your help!

The job didn't run because it did not allow the use of third-party orbs.
<kbd>ScreenShot-2019-07-23-13 42 50</kbd>

By changing this setting, it was confirmed that the test succeeded.
https://circleci.com/gh/ishikawa999/redmine_message_customize

The automated execution of tests in CircleCI makes this plugin easier to develop. Thank you for everything.

**Pull request merged**
